{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNewO4vLgZcpkC463o5nWPa",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/qasimshah0321/pythonprojects/blob/main/Assignment_7_Movie_Ticket_Booking_System_Muhammad_Qasim.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "z42I4SAS8-yr",
        "outputId": "ae9fbee7-450f-4aed-d48c-f9734c013edb"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Welcome to Movie Ticket Booking\n",
            "1. View Movies\n",
            "2. Book Ticket\n",
            "3. Cancel Ticket\n",
            "4. Show Booking Summary\n",
            "5. Exit\n",
            "Choose option: 1\n",
            "\n",
            "Available Movies and Showtimes:\n",
            "Avengers (6PM): 20 seats\n",
            "Avengers (9PM): 15 seats\n",
            "Inception (5PM): 10 seats\n",
            "Inception (8PM): 12 seats\n",
            "\n",
            "Welcome to Movie Ticket Booking\n",
            "1. View Movies\n",
            "2. Book Ticket\n",
            "3. Cancel Ticket\n",
            "4. Show Booking Summary\n",
            "5. Exit\n",
            "Choose option: 2\n",
            "Enter movie name: Avengers \n",
            "Movie not found.\n",
            "\n",
            "Welcome to Movie Ticket Booking\n",
            "1. View Movies\n",
            "2. Book Ticket\n",
            "3. Cancel Ticket\n",
            "4. Show Booking Summary\n",
            "5. Exit\n",
            "Choose option: Avengers\n",
            "Invalid choice. Try again.\n",
            "\n",
            "Welcome to Movie Ticket Booking\n",
            "1. View Movies\n",
            "2. Book Ticket\n",
            "3. Cancel Ticket\n",
            "4. Show Booking Summary\n",
            "5. Exit\n",
            "Choose option: 2\n",
            "Enter movie name: Avengers\n",
            "Enter show time (e.g. 6PM): 9PM\n",
            "Enter number of tickets: 3\n",
            "Booking confirmed for Avengers at 9PM (3 tickets)\n",
            "\n",
            "Welcome to Movie Ticket Booking\n",
            "1. View Movies\n",
            "2. Book Ticket\n",
            "3. Cancel Ticket\n",
            "4. Show Booking Summary\n",
            "5. Exit\n",
            "Choose option: 4\n",
            "\n",
            "📄 Booking Summary:\n",
            "- Avengers | 9PM | 3 tickets\n",
            "\n",
            "Welcome to Movie Ticket Booking\n",
            "1. View Movies\n",
            "2. Book Ticket\n",
            "3. Cancel Ticket\n",
            "4. Show Booking Summary\n",
            "5. Exit\n",
            "Choose option: 5\n",
            "Thank you for using Movie Ticket Booking System!\n"
          ]
        }
      ],
      "source": [
        "movies = {\n",
        "    \"Avengers\": {\"6PM\": 20, \"9PM\": 15},\n",
        "    \"Inception\": {\"5PM\": 10, \"8PM\": 12}\n",
        "}\n",
        "\n",
        "bookings = []\n",
        "\n",
        "def display_movies():\n",
        "    print(\"\\nAvailable Movies and Showtimes:\")\n",
        "    for movie, shows in movies.items():\n",
        "        for time, seats in shows.items():\n",
        "            print(f\"{movie} ({time}): {seats} seats\")\n",
        "\n",
        "def book_ticket():\n",
        "    movie = input(\"Enter movie name: \").strip.title()\n",
        "    if movie not in movies:\n",
        "        print(\"Movie not found.\")\n",
        "        return\n",
        "\n",
        "    showtime = input(\"Enter show time (e.g. 6PM): \").upper()\n",
        "    if showtime not in movies[movie]:\n",
        "        print(\"Showtime not available.\")\n",
        "        return\n",
        "\n",
        "    try:\n",
        "        tickets = int(input(\"Enter number of tickets: \"))\n",
        "    except ValueError:\n",
        "        print(\"Invalid number.\")\n",
        "        return\n",
        "\n",
        "    if tickets <= movies[movie][showtime]:\n",
        "        movies[movie][showtime] -= tickets\n",
        "        bookings.append({\"movie\": movie, \"time\": showtime, \"tickets\": tickets})\n",
        "        print(f\"Booking confirmed for {movie} at {showtime} ({tickets} tickets)\")\n",
        "    else:\n",
        "        print(\"Not enough seats available.\")\n",
        "\n",
        "def cancel_ticket():\n",
        "    movie = input(\"Enter movie name to cancel: \").title()\n",
        "    showtime = input(\"Enter showtime to cancel: \").upper()\n",
        "\n",
        "    found = False\n",
        "    for booking in bookings:\n",
        "        if booking[\"movie\"] == movie and booking[\"time\"] == showtime:\n",
        "            movies[movie][showtime] += booking[\"tickets\"]\n",
        "            print(f\"Canceled {booking['tickets']} ticket(s) for {movie} at {showtime}\")\n",
        "            bookings.remove(booking)\n",
        "            found = True\n",
        "            break\n",
        "\n",
        "    if not found:\n",
        "        print(\"No matching booking found.\")\n",
        "\n",
        "def show_summary():\n",
        "    print(\"\\n📄 Booking Summary:\")\n",
        "    if not bookings:\n",
        "        print(\"No bookings yet.\")\n",
        "    else:\n",
        "        for b in bookings:\n",
        "            print(f\"- {b['movie']} | {b['time']} | {b['tickets']} tickets\")\n",
        "\n",
        "while True:\n",
        "    print(\"\\nWelcome to Movie Ticket Booking\")\n",
        "    print(\"1. View Movies\")\n",
        "    print(\"2. Book Ticket\")\n",
        "    print(\"3. Cancel Ticket\")\n",
        "    print(\"4. Show Booking Summary\")\n",
        "    print(\"5. Exit\")\n",
        "\n",
        "    choice = input(\"Choose option: \")\n",
        "\n",
        "    if choice == '1':\n",
        "        display_movies()\n",
        "    elif choice == '2':\n",
        "        book_ticket()\n",
        "    elif choice == '3':\n",
        "        cancel_ticket()\n",
        "    elif choice == '4':\n",
        "        show_summary()\n",
        "    elif choice == '5':\n",
        "        print(\"Thank you for using Movie Ticket Booking System!\")\n",
        "        break\n",
        "    else:\n",
        "        print(\"Invalid choice. Try again.\")\n"
      ]
    }
  ]
}