{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMPHV0+OpxBE0c/FG/E4Hgf",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/qasimshah0321/pythonprojects/blob/main/Assignment_7_Car_Rental_System_Muhammad_Qasim.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "cnxkexPQGyZZ",
        "outputId": "0cc61299-a470-4d9c-a0ba-73b79686e3cf"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Welcome to Car Rental\n",
            "1. View Cars\n",
            "2. Rent Car\n",
            "3. Return Car\n",
            "4. Rentals\n",
            "5. Exit\n",
            "Choose option: 4\n",
            "Rented Cars:\n",
            "- Toyota Corolla -> Ali\n",
            "\n",
            "Welcome to Car Rental\n",
            "1. View Cars\n",
            "2. Rent Car\n",
            "3. Return Car\n",
            "4. Rentals\n",
            "5. Exit\n",
            "Choose option: 1\n",
            "Available cars:\n",
            "- Honda Civic\n",
            "- Suzuki Alto\n",
            "\n",
            "Welcome to Car Rental\n",
            "1. View Cars\n",
            "2. Rent Car\n",
            "3. Return Car\n",
            "4. Rentals\n",
            "5. Exit\n",
            "Choose option: 3\n",
            "Enter car name: Toyota Corolla\n",
            "Car returned successfully from Ali\n",
            "\n",
            "Welcome to Car Rental\n",
            "1. View Cars\n",
            "2. Rent Car\n",
            "3. Return Car\n",
            "4. Rentals\n",
            "5. Exit\n",
            "Choose option: 1\n",
            "Available cars:\n",
            "- Honda Civic\n",
            "- Suzuki Alto\n",
            "- Toyota Corolla\n",
            "\n",
            "Welcome to Car Rental\n",
            "1. View Cars\n",
            "2. Rent Car\n",
            "3. Return Car\n",
            "4. Rentals\n",
            "5. Exit\n",
            "Choose option: 2\n",
            "Enter car name: Honda Civic\n",
            "Enter your name: Qasim\n",
            "Car rented successfully to Qasim\n",
            "\n",
            "Welcome to Car Rental\n",
            "1. View Cars\n",
            "2. Rent Car\n",
            "3. Return Car\n",
            "4. Rentals\n",
            "5. Exit\n",
            "Choose option: 4\n",
            "Rented Cars:\n",
            "- Honda Civic -> Qasim\n",
            "\n",
            "Welcome to Car Rental\n",
            "1. View Cars\n",
            "2. Rent Car\n",
            "3. Return Car\n",
            "4. Rentals\n",
            "5. Exit\n",
            "Choose option: 5\n",
            "Thank you for using the Car Rental System. Goodbye!\n"
          ]
        }
      ],
      "source": [
        "cars = {\n",
        "    \"honda civic\": {\"available\": True, \"renter\": None},\n",
        "    \"suzuki alto\": {\"available\": True, \"renter\": None},\n",
        "    \"toyota corolla\": {\"available\": False, \"renter\": \"Ali\"}\n",
        "}\n",
        "\n",
        "def view_available_cars():\n",
        "    available = []\n",
        "    for car, info in cars.items():\n",
        "        if info[\"available\"]:\n",
        "            car_name = car.title()\n",
        "            available.append(car_name)\n",
        "    if available:\n",
        "        print(\"Available cars:\")\n",
        "        for car in available:\n",
        "            print(f\"- {car}\")\n",
        "    else:\n",
        "        print(\"No cars are currently available.\")\n",
        "\n",
        "def rent_car():\n",
        "    car_name = input(\"Enter car name: \").lower()\n",
        "    if car_name in cars and cars[car_name][\"available\"]:\n",
        "        renter_name = input(\"Enter renter name: \")\n",
        "        cars[car_name][\"available\"] = False\n",
        "        cars[car_name][\"renter\"] = renter_name\n",
        "        print(f\"Car rented successfully to {renter_name}\")\n",
        "    else:\n",
        "        print(\"Car not available or does not exist.\")\n",
        "\n",
        "def return_car():\n",
        "    car_name = input(\"Enter car name: \").lower()\n",
        "    if car_name in cars and not cars[car_name][\"available\"]:\n",
        "        cars[car_name][\"available\"] = True\n",
        "        renter = cars[car_name][\"renter\"]\n",
        "        cars[car_name][\"renter\"] = None\n",
        "        print(f\"Car returned successfully from {renter}\")\n",
        "    else:\n",
        "        print(\"Car is not currently rented or does not exist.\")\n",
        "\n",
        "def view_rentals():\n",
        "    print(\"Rented Cars:\")\n",
        "    found = False\n",
        "    for car, info in cars.items():\n",
        "        if not info[\"available\"]:\n",
        "            print(f\"- {car.title()} -- {info['renter']}\")\n",
        "            found = True\n",
        "    if not found:\n",
        "        print(\"No active rentals.\")\n",
        "\n",
        "# Main menu loop\n",
        "while True:\n",
        "    print(\"\\nWelcome to Car Rental\")\n",
        "    print(\"1. View Cars\")\n",
        "    print(\"2. Rent Car\")\n",
        "    print(\"3. Return Car\")\n",
        "    print(\"4. Rentals\")\n",
        "    print(\"5. Exit\")\n",
        "\n",
        "    choice = input(\"Choose option: \")\n",
        "\n",
        "    if choice == \"1\":\n",
        "        view_available_cars()\n",
        "    elif choice == \"2\":\n",
        "        rent_car()\n",
        "    elif choice == \"3\":\n",
        "        return_car()\n",
        "    elif choice == \"4\":\n",
        "        view_rentals()\n",
        "    elif choice == \"5\":\n",
        "        print(\"Thank you for using the Car Rental System. Goodbye!\")\n",
        "        break\n",
        "    else:\n",
        "        print(\"Invalid option. Please try again.\")\n"
      ]
    }
  ]
}